// Every UI string. Japanese will be a translation of this file, not a refactor.
export const en = {
  site: {
    name: "Ludion",
    description: "Ludion is a public, writable AI model. People teach it, machines verify every lesson, and every assistant can use it.",
  },
  nav: {
    label: "Main",
    lessons: "Lessons",
  },
  home: {
    title: "Ludion: teach it once",
    headline: "Teach it once.",
    sub: "Everyone's AI learns it in minutes. Your name stays on it.",
    replayTitle: "How a lesson passes",
    checking: "Checking",
    replay: (by: "test" | "proof" | "source", date: string) =>
      `A replay of how this lesson passed: ${by === "test" ? "CI ran its test" : by === "proof" ? "Lean checked its proof" : "its quote was found on the source page"}, and it was verified on ${date}.`,
    logTitle: (by: "test" | "proof" | "source", runner: string) => (by === "source" ? "Source check" : by === "proof" ? "Proof check (lean)" : `Test (${runner})`),
    recent: "Recently verified",
    seeLessons: "See all lessons",
  },
  lessons: {
    title: "Lessons",
    intro: (shown: number, total: number) =>
      shown < total ? `The newest ${shown} of ${total} lessons.` : total === 1 ? "1 lesson." : `${total} lessons, newest first.`,
    empty: "No lessons yet.",
  },
  lesson: {
    verifiedBy: { test: "Verified by test", proof: "Verified by proof", source: "Verified by source" },
    on: (date: string) => `on ${date}`,
    appliesTo: (subject: string, version?: string | null) => `Applies to ${subject}${version ? ` ${version}` : ""}`,
    taughtBy: "Taught by",
    evidence: "Evidence",
    test: (runner: string) => `Test (${runner})`,
    proof: "Proof (Lean)",
    mark: { test: "exit 0", proof: "proved", source: "quote found" },
    source: "Source",
    copy: "Copy",
    copied: "Copied",
    corrects: "Corrects",
    correctedBy: "This lesson was corrected by",
    viewFile: "View the file on GitHub",
    pullRequest: (n: number) => `Pull request #${n}`,
  },
  record: {
    verified: "Verified",
    appliesTo: "Applies to",
    teacher: "Teacher",
    check: "Check it yourself",
  },
  teacher: {
    title: (login: string) => `@${login} on Ludion`,
    summary: (lessons: number, subjects: number) =>
      `${lessons} ${lessons === 1 ? "lesson" : "lessons"} in ${subjects} ${subjects === 1 ? "subject" : "subjects"}`,
    profile: "GitHub profile",
    subjects: "Subjects",
  },
  teach: {
    title: "Teach Ludion",
    h1: "Teach Ludion",
    intro: "Your GitHub name is shown on every lesson you teach.",
    closed: "Teaching on Ludion opens soon. Nothing was saved.",
    signIn: "Sign in with GitHub",
    signInToSign: "Sign in with GitHub to sign this lesson",
    sourcesAfterSignIn: "Sources are checked after you sign in.",
    draftHeading: "The lesson you will sign",
    subject: "Subject",
    version: "Version",
    claim: "Claim",
    evidence: "Evidence",
    test: (runner: string) => (runner === "lean" ? "Proof (Lean)" : `Test (${runner})`),
    expectFail: (error: string) => `Expected to fail with: ${error}`,
    source: "Source",
    noVersion: "any version",
    signingAs: (login: string) => `You are signing as @${login}.`,
    // Placeholder: the owner decides the final wording of the license and consent line.
    consent:
      "By pressing Teach, you publish this lesson under CC BY-SA 4.0 with your GitHub name on it, and you confirm that you wrote the claim and that the evidence supports it.",
    check: "Check",
    checking: "Checking…",
    teach: "Teach",
    edit: "Edit",
    review: "Review",
    quoteFound: (host: string) => `Quote found on ${host}`,
    ciWillRun: "CI will run this test",
    submitted: (pr: number) => `Pull request #${pr} is open in your name.`,
    prVerified: "Verified. Live for everyone in a few minutes.",
    prFailed: "CI could not verify this lesson.",
    prChecks: "See the checks",
    openLesson: "Open the lesson",
    form: {
      heading: "Write a lesson",
      subjectHint: "lowercase, like python or wrangler",
      versionHint: "for example >=3.12",
      claimHint: "One sentence. Write it the way you would tell a colleague.",
      addTest: "Add a test",
      testN: (n: number) => `Test ${n}`,
      sourceN: (n: number) => `Source ${n}`,
      addSource: "Add a source",
      remove: "Remove",
      runner: "Runner",
      code: "Code",
      codeHint: "Exits 0 only if the claim is true.",
      url: "URL",
      quote: "Quote",
      quoteHint: "Paste an exact sentence from the page.",
      counter: (n: number) => `${n}/400`,
    },
    errors: {
      signin_required: "Sign in with GitHub to teach.",
      account_too_new: "GitHub accounts must be at least 30 days old to teach. This keeps spam out of Ludion.",
      invalid_draft: "The draft has problems:",
      source_not_found: "This source could not be confirmed. Link to a public https page and copy a sentence exactly as it appears there.",
      rate_limited: "You've checked too many lessons in the last minute. Wait a minute and try again.",
      unknown_replaces: "The lesson you're correcting isn't active anymore. Check its link.",
      daily_limit: "You've taught 20 lessons today. Come back tomorrow.",
      github_error: "GitHub didn't respond. Nothing was published. Try again in a minute.",
      teaching_not_open: "Teaching on Ludion opens soon. Nothing was saved.",
      unknown: "Something went wrong. Nothing was published. Try again in a minute.",
      badDraftLink: "This signing link is damaged. Ask your assistant for a new one.",
    } as Record<string, string>,
  },
  footer: {
    count: (lessons: number, teachers: number) =>
      `${lessons} ${lessons === 1 ? "lesson" : "lessons"} from ${teachers} ${teachers === 1 ? "teacher" : "teachers"}.`,
    license: "Lessons are CC BY-SA 4.0. Code is Apache-2.0.",
    github: "GitHub",
  },
  notFound: {
    title: "No page here",
    body: "No page here.",
    search: "Search the lessons",
    rest: " or teach one.",
  },
};

const dateFormat = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
/** "Oct 8, 2026" */
export const formatDate = (iso: string): string => dateFormat.format(new Date(iso));
