import { Ajv2020 } from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

// Ajv's standalone ESM output still require()s this runtime helper. It counts code points,
// so inline it: the generated module then has no imports and runs in Node, Workers, and browsers.
const UCS2_REQUIRE = 'require("ajv/dist/runtime/ucs2length").default';
const UCS2_INLINE = "((s) => { let n = 0; for (const _ of s) n++; return n; })";

export function generateValidatorSource(schemaJson: string, schemaFile = "lessons.schema.json"): string {
  const ajv = new Ajv2020({ allErrors: true, strict: true, code: { source: true, esm: true } });
  const validate = ajv.compile(JSON.parse(schemaJson));
  const code = standaloneCode.default(ajv, validate).replaceAll(UCS2_REQUIRE, UCS2_INLINE);
  if (code.includes("require(")) {
    throw new Error("The generated validator needs an Ajv runtime helper that is not inlined. Add it to validator-source.ts.");
  }
  return `// Generated by packages/core/scripts/gen-validator.ts from lessons/${schemaFile}. Do not edit.\n` + code + "\n";
}
