export type * from "./types.ts";
export { lessonValidator, validateLesson, validateLessonV0, validateLessonV1, type FieldError, type LessonValidator, type ValidationResult } from "./schema.ts";
export { isV1 } from "./types.ts";
export { claimOf, generateClaim, lessonProblems, quotesMissingSymbol, subjectFor, ungroundedWords, versionOf } from "./claim.ts";
export type { AjvError, ValidateFn } from "./generated/validate-lesson.js";
export { newId } from "./ulid.ts";
export { formatLesson } from "./format.ts";
export { activeSet } from "./active.ts";
export { search, type SearchOptions } from "./search.ts";
export { buildIndex, storedLogin, type GitInfo, type BuildOptions } from "./index-builder.ts";
export { resolveLogins, type FetchFn } from "./teachers.ts";
export { checkSource, normalizeText, sourceUrlProblem, type SourceResult } from "./source-check.ts";
export { asTest, isDifferential, pinInRange, verifiedBy } from "./label.ts";
