export type * from "./types.ts";
export { validateLesson, type FieldError, type ValidationResult } from "./schema.ts";
export { newId } from "./ulid.ts";
export { formatLesson } from "./format.ts";
export { activeSet } from "./active.ts";
export { search, type SearchOptions } from "./search.ts";
export { buildIndex, storedLogin, type GitInfo, type BuildOptions } from "./index-builder.ts";
export { resolveLogins, type FetchFn } from "./teachers.ts";
export { checkSource, normalizeText, sourceUrlProblem, type SourceResult } from "./source-check.ts";
export { verifiedBy } from "./label.ts";
