export type * from "./types.ts";
export { lessonValidator, validateLesson, type FieldError, type LessonValidator, type ValidationResult } from "./schema.ts";
export type { AjvError, ValidateFn } from "./generated/validate-lesson.js";
export { newId } from "./ulid.ts";
export { formatLesson } from "./format.ts";
export { activeSet } from "./active.ts";
export { search, type SearchOptions } from "./search.ts";
export { buildIndex, storedLogin, type GitInfo, type BuildOptions } from "./index-builder.ts";
export { resolveLogins, type FetchFn } from "./teachers.ts";
export { checkSource, normalizeText, sourceUrlProblem, type SourceResult } from "./source-check.ts";
export { verifiedBy } from "./label.ts";
export { ASK_HEADER, NO_MATCH, formatAsk, lessonUrl, toAskLesson, type AskLesson, type AskSource } from "./ask-text.ts";
