/**
 * CLI: pnpm sync-readme
 *
 * Gate 3-B (D1): there is ONE authored README — the repo root README.md. The
 * npm package (`ludion-router`) publishes router/README.md, which npm
 * auto-includes in the tarball regardless of package.json "files". To stop the
 * npm page from drifting into a weaker copy (the Gate 3-A F2 finding), the
 * router README is a generated byte-for-byte copy of the root one.
 *
 * The root README uses absolute URLs throughout precisely so the copy is correct
 * on npm, where router/package.json's `repository.directory: "router"` would
 * otherwise rewrite relative links to a non-existent router/ subpath.
 *
 * CI runs this and then `git diff --exit-code`, so a hand-edit of
 * router/README.md (or a stale sync) fails the build — the same structural guard
 * the report-data generator uses.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const src = join(repoRoot, "README.md");
const dest = join(repoRoot, "router", "README.md");

const before = readFileSync(src, "utf-8");
const existing = readFileSync(dest, "utf-8");

if (existing === before) {
  console.log("sync-readme: router/README.md already in sync");
} else {
  writeFileSync(dest, before);
  console.log("sync-readme: router/README.md updated from root README.md");
}
